// export const presaleAbi = [
//   { type: "constructor", inputs: [], stateMutability: "nonpayable" },
//   {
//     type: "function",
//     name: "buyTokens",
//     inputs: [{ name: "tokenAmount", type: "uint256", internalType: "uint256" }],
//     outputs: [],
//     stateMutability: "payable",
//   },
//   {
//     type: "function",
//     name: "hardCap",
//     inputs: [],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "initialize",
//     inputs: [
//       { name: "_tokenAddress", type: "address", internalType: "address" },
//       { name: "_tokenPrice", type: "uint256", internalType: "uint256" },
//       { name: "_minPurchase", type: "uint256", internalType: "uint256" },
//       { name: "_maxPurchase", type: "uint256", internalType: "uint256" },
//       { name: "_hardCap", type: "uint256", internalType: "uint256" },
//       { name: "_devAddress", type: "address", internalType: "address" },
//     ],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "maxPurchase",
//     inputs: [],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "minPurchase",
//     inputs: [],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "owner",
//     inputs: [],
//     outputs: [{ name: "", type: "address", internalType: "address" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "pausePresale",
//     inputs: [],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "presaleActive",
//     inputs: [],
//     outputs: [{ name: "", type: "bool", internalType: "bool" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "proxiableUUID",
//     inputs: [],
//     outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "referralEarnings",
//     inputs: [{ name: "", type: "address", internalType: "address" }],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "referralPercentages",
//     inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "referrers",
//     inputs: [{ name: "", type: "address", internalType: "address" }],
//     outputs: [{ name: "", type: "address", internalType: "address" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "renounceOwnership",
//     inputs: [],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "setReferrer",
//     inputs: [{ name: "_referrer", type: "address", internalType: "address" }],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "soldTokens",
//     inputs: [],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "startPresale",
//     inputs: [],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "tokenAddress",
//     inputs: [],
//     outputs: [{ name: "", type: "address", internalType: "address" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "tokenPrice",
//     inputs: [],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "tokensPurchased",
//     inputs: [{ name: "", type: "address", internalType: "address" }],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "totalRaised",
//     inputs: [],
//     outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
//     stateMutability: "view",
//   },
//   {
//     type: "function",
//     name: "transferOwnership",
//     inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "updateDevAddress",
//     inputs: [
//       { name: "_newDevAddress", type: "address", internalType: "address" },
//     ],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "updateDevFee",
//     inputs: [{ name: "_percent", type: "uint256", internalType: "uint256" }],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "updatePresaleParams",
//     inputs: [
//       { name: "_tokenPrice", type: "uint256", internalType: "uint256" },
//       { name: "_minPurchase", type: "uint256", internalType: "uint256" },
//       { name: "_maxPurchase", type: "uint256", internalType: "uint256" },
//       { name: "_hardCap", type: "uint256", internalType: "uint256" },
//     ],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "updateReferralPercentages",
//     inputs: [
//       {
//         name: "_percentages",
//         type: "uint256[5]",
//         internalType: "uint256[5]",
//       },
//     ],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "upgradeTo",
//     inputs: [
//       { name: "newImplementation", type: "address", internalType: "address" },
//     ],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "function",
//     name: "upgradeToAndCall",
//     inputs: [
//       { name: "newImplementation", type: "address", internalType: "address" },
//       { name: "data", type: "bytes", internalType: "bytes" },
//     ],
//     outputs: [],
//     stateMutability: "payable",
//   },
//   {
//     type: "function",
//     name: "withdrawFunds",
//     inputs: [],
//     outputs: [],
//     stateMutability: "nonpayable",
//   },
//   {
//     type: "event",
//     name: "AdminChanged",
//     inputs: [
//       {
//         name: "previousAdmin",
//         type: "address",
//         indexed: false,
//         internalType: "address",
//       },
//       {
//         name: "newAdmin",
//         type: "address",
//         indexed: false,
//         internalType: "address",
//       },
//     ],
//     anonymous: false,
//   },
//   {
//     type: "event",
//     name: "BeaconUpgraded",
//     inputs: [
//       {
//         name: "beacon",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//     ],
//     anonymous: false,
//   },
//   {
//     type: "event",
//     name: "Initialized",
//     inputs: [
//       {
//         name: "version",
//         type: "uint8",
//         indexed: false,
//         internalType: "uint8",
//       },
//     ],
//     anonymous: false,
//   },
//   {
//     type: "event",
//     name: "OwnershipTransferred",
//     inputs: [
//       {
//         name: "previousOwner",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//       {
//         name: "newOwner",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//     ],
//     anonymous: false,
//   },
//   { type: "event", name: "PresalePaused", inputs: [], anonymous: false },
//   { type: "event", name: "PresaleStarted", inputs: [], anonymous: false },
//   {
//     type: "event",
//     name: "ReferralPaid",
//     inputs: [
//       {
//         name: "referee",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//       {
//         name: "referrer",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//       {
//         name: "level",
//         type: "uint256",
//         indexed: false,
//         internalType: "uint256",
//       },
//       {
//         name: "amount",
//         type: "uint256",
//         indexed: false,
//         internalType: "uint256",
//       },
//     ],
//     anonymous: false,
//   },
//   {
//     type: "event",
//     name: "TokensPurchased",
//     inputs: [
//       {
//         name: "buyer",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//       {
//         name: "amount",
//         type: "uint256",
//         indexed: false,
//         internalType: "uint256",
//       },
//       {
//         name: "cost",
//         type: "uint256",
//         indexed: false,
//         internalType: "uint256",
//       },
//     ],
//     anonymous: false,
//   },
//   {
//     type: "event",
//     name: "TokensWithdrawn",
//     inputs: [
//       {
//         name: "user",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//       {
//         name: "amount",
//         type: "uint256",
//         indexed: false,
//         internalType: "uint256",
//       },
//     ],
//     anonymous: false,
//   },
//   {
//     type: "event",
//     name: "Upgraded",
//     inputs: [
//       {
//         name: "implementation",
//         type: "address",
//         indexed: true,
//         internalType: "address",
//       },
//     ],
//     anonymous: false,
//   },
// ];
